export  const bb_1="../../assets/bb-1.jpg"
export  const bb_2="../../assets/bb-2.jpg"
export  const bb_3="../../assets/bb-3.jpg"
export  const bb_4="../../assets/bb-4.jpg"
export  const modal_bg="../../assets/modal_bg.jpg"
export  const result_bg="../../assets/result_bg.jpg"